### ISSUE TITLE
UInt32 Overflow  in WANCommonInterfaceConfigClient

### ISSUE THREAD

**Issue by RalfWenzel** [inflames2k/PS.FritzBox.API#11]
Hallo, wenn man die API gegen eine Box laufen lässt, die schon lange in Betrieb ist,  werfen die 
GetTotal<Packets|Bytes><Send|Received>Async() Methoden in WANCommonInterfaceConfigClient eine Ausnahme weil das Ergebnis nicht in einen UInt32 passt. Schlage vor, dass du auf UInt64 änderst.
Gruß, Ralf.

**Comment by inflames2k** [comment]
Ich werde das in der nächsten Version korrigieren. - Was mich wundert, ist dass es laut AVM-Dokumentation eigentlich nur ein 16 bit Wert ist.

**Comment by RalfWenzel** [comment]
Ich denke das ist ein Copy/Paste Error bei AVM. Wenn man mal drüber nachdenkt,...Total Bytes seit die Box läuft.... die 4 GB sind da schnell voll. Ansonsten Respekt für deine Arbeit. Was mir am Rand noch einfällt...Ich habe ein eigenes Discovery und deines nur kurz ausprobiert. Lief nur, nachdem ich IPv6 abgeschaltet hatte. Config: Lenovo W530 mit Dockingstation, Ethernet über Kabel, IPv4 und IPv6 aktiviert. Schau mal ob du das nachvollziehen kannst, wenn nicht, melde dich noch mal, dann schau ich mal genau wo es knallt.

**Comment by inflames2k** [comment]
Was heißt denn, du hast ein eigenes Discovery? - Wie funktioniert denn dein Discovery bzw. was funktioniert denn da anders als bei meinem?

**Comment by inflames2k** [comment]
Seit längerem im Code vorhanden und wird nach den weiteren offenen Korrekturen im Update nachgeliefert.
