### ISSUE TITLE
crash in PS.FritzBox.API.CMD / DiscoverAsync

### ISSUE THREAD

**Issue by donid** [inflames2k/PS.FritzBox.API#12]
Ich bekomme beim Start des Konsolenprojekts mehrere Exceptions und dann stürzt das Programm ab.
Es könnte sich hier um das gleiche Problem handeln, wie in https://github.com/inflames2k/PS.FritzBox.API/issues/11#issuecomment-427598491 beschrieben.

Die erste Exception ist:
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
An invalid argument was supplied

Mit dem Callstack:
>	System.dll!System.Net.Sockets.Socket.SetSocketOption(System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, int optionValue, bool silent) Line 6491	C#
 	System.dll!System.Net.Sockets.Socket.SetSocketOption(System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, int optionValue) Line 2307	C#
 	PS.FritzBox.API.dll!PS.FritzBox.API.DeviceLocator.BeginSendReceiveAsync(System.Net.IPAddress broadcastAddress = {System.Net.IPAddress}, int index = 0x0000000c, System.Action<PS.FritzBox.API.FritzDevice> callback = {Method = {System.Reflection.RuntimeMethodInfo}}) Line 85	C#
 	PS.FritzBox.API.dll!PS.FritzBox.API.DeviceLocator.DiscoverBroadcast(System.Action<PS.FritzBox.API.FritzDevice> callback = {Method = {System.Reflection.RuntimeMethodInfo}}) Line 70	C#
 	PS.FritzBox.API.dll!PS.FritzBox.API.DeviceLocator.FindDevicesAsync() Line 44	C#
 	PS.FritzBox.API.dll!PS.FritzBox.API.DeviceLocator.DiscoverAsync() Line 26	C#
 	PS.FritzBox.API.CMD.exe!PS.FritzBox.API.CMD.Program.GetDevices() Line 81	C#
 	PS.FritzBox.API.CMD.exe!PS.FritzBox.API.CMD.Program.Main(string[] args = {string[0x00000000]}) Line 18	C#

Bei meiner FritzBox ist auch IPv4 und IPv6 aktiv.

**Comment by inflames2k** [comment]
Muss ich mir anschauen. Hab gerade keine Idee, woran das liegen könnte.

**Comment by inflames2k** [comment]
After pull request from @IronFE the bug should be fixed. - I will roll out a new version soon. - The changed source code is allready available in the repository.
