### ISSUE TITLE
Erweiterung von 5Ghz und Gäste Wlan

### ISSUE THREAD

**Issue by supercop89** [inflames2k/PS.FritzBox.API#14]
Eine Möglichkeit wäre noch die Erweiterung der Kontrolle des 5 Ghz und des Gäste WLANs mittels der Befehle:

/upnp/control/wlanconfig2
/upnp/control/wlanconfig3

Hab ich etwas übersehen? Meiner Meinung müsste derzeit nur der Service #1 von der FritzBox steuerbar sein.

**Comment by supercop89** [comment]
Wäre hier eine Adaptierung möglich?

**Comment by inflames2k** [comment]
Nun ja, für wlanconfig2 und wlanconfig3 gibt es keine Dokumentation. - Ich werde mal sehen, ob es sich eventuell dennoch steuern lässt (über den URN).

//EDIT: Also ich habe jetzt Service 2 und 3 ergänzt (in meiner Entwicklungsversion). - Funktionieren erst einmal scheinbar gut. - Damit schließe ich hier nun doch erst einmal ab.

Service 2 ist dann wie wahrscheinlich bekannt das 5GHz Netz und Service 3 das Gästenetzwerk.

**Comment by inflames2k** [comment]
War wohl doch irgend etwas anderes. Ging davon aus, die wären nicht aufrufbar da ich direkt eine Exception bekam. - Setze gerade WLANConfiguration2 Service (für 5 GHz) um und im Anschluss das Gästenetz.

**Comment by supercop89** [comment]
Korrekt, so funktioniert es.

Danke, bist meiner Antwort zuvorgekommen..
