### ISSUE TITLE
Fritz OS 7.10 no Reboot

### ISSUE THREAD

**Issue by talun2075** [inflames2k/PS.FritzBox.API#15]
Hi,
thanks for the Work . I use this Lib to reboot my Fritz!box each night. After the Update to OS 7.10 on my 7590, I can´t reboot and got the Error "An error occurred while sending the request."

Maybe you have Time an can look on it?

Thanks.

HI,
danke für die Arbeit, die Du Dir gemacht hast. Ich nutze die Bilbliothek um meine 7590 jeden abend neu zu starten. Nach dem Update auf die neue OS Version 7.10 bekomme ich allerdings den Fehler: "An error occurred while sending the request."

Wäre schön, wenn Du Dir die Zeit nehmen könntest da mal nach zusehen. 

Danke Dir.
Rein für die Zukunft, ist deutsch oder englisch besser?

Gruß
Frank

**Comment by inflames2k** [comment]
Hallo,

hier muss ich wohl leider erst einmal warten, bis meine Box das Update bekommt. Habe aktuell die 7.02 und laut automatischer Suche steht aktuell kein Update bereit.

Sobald ich die 7.1 drauf habe, werde ich mich dem Problem mal annehmen.

**Comment by talun2075** [comment]
Super, dann warte ich so lange. Danke!

**Comment by talun2075** [comment]
Ich habe mal geschaut Du scheinst noch alles richtig zu machen aber die haben scheinbar etwas geändert. in der SoabClient.cs beim senden:
HttpResponseMessage response = await client.SendAsync(request);
tritt der Fehler auf. das ist natürlich schade, weil keine richtige Fehlermeldung erscheint. 
Hoffe Du bekommst das Update bald und verstehst warum das da knallt, bin froh, dass ich mich bisher nicht einlesen mußte.

**Comment by inflames2k** [comment]
Über welche Methode hast du den Reboot probiert? Über den DeviceConfigClient wird der Reboot ausgeführt. Kann daher erst einmal das Problem nicht erkennen.

**Comment by inflames2k** [comment]
Since the problem cannot be traced and others perform the reboot cleanly, closed.
