### ISSUE TITLE
WANDSLInterfaceConfig missing?

### ISSUE THREAD

**Issue by donid** [inflames2k/PS.FritzBox.API#16]
I couldn't find the WANDSLInterfaceConfig service. Any special reason that it is missing, or do you simply not own a box with DSL?

**Comment by inflames2k** [comment]
At the moment I'm on fixing all open issues. After that has been done I check the integration of the WANDSLInterfaceConfig service.

If anything else is missing feel free to request.

**Comment by inflames2k** [comment]
I added the service now and will Update the package and the source today.

**Comment by donid** [comment]
I had done my own implementation in the  meantime (inspired by some powershell code that I found online), I have compare that to your code and found that you seem to have a typo here:
WANDSLInterfaceStatistics.**LinkRetreain** -> should be Retrain?
Another difference was, that your code is missing "New" in the string portion of this code:
`ATURCountry = document.Descendants("NewATURCountry").First().Value;`
And lastly my code had an additional property in WANDSLInterfaceStatistics:
`TransmitBlocks = Convert.ToUInt32(document.Descendants("NewTransmitBlocks").First().Value);`

**Comment by inflames2k** [comment]
>> WANDSLInterfaceStatistics.LinkRetreain -> should be Retrain?

You are right, I will fix this.

>> Another difference was, that your code is missing "New" in the string portion of this code:

Here you are also right but it's suprising that for me calling the interface succeeded. I will check this.

>> And lastly my code had an additional property in WANDSLInterfaceStatistics: 

This Property is contained in the class and is read on line 97 of WANDSLInterfaceConfigClient.cs

**Comment by inflames2k** [comment]
Typo and missing "New" are fixed.

**Comment by donid** [comment]
I have just updated to the new version and it works great. Thanks.
