### ISSUE TITLE
Consider Pdb-symbols-package creation and publication to nuget.org

### ISSUE THREAD

**Issue by donid** [inflames2k/PS.FritzBox.API#17]
I haven't tried this myself yet, but according to https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg is should be pretty easy - just add the xml snippet to the .csproj and VS will create an .snupkg, which you then can publish to nuget.org

**Comment by inflames2k** [comment]
I'll try it this evening and will upload the new version to nuget.org if it's working.

**Comment by inflames2k** [comment]
Hello,

I fixed the issues of the other report and created the symbol package. - Its uploaded to nuget.

**Comment by donid** [comment]
Works great - Thanks!
