### ISSUE TITLE
Port & Pathname changed?

### ISSUE THREAD

**Issue by Stephanowicz** [inflames2k/PS.FritzBox.API#2]
Hi,
first of all thanx for Your work!

I'm not sure if it's model related, but I had to change the port and the pathnames in order to get it working:

for the connection:  `...("http://fritz.box:49000", 10000);`
and all paths with **/tr064** like `string ControlUrl => "/tr064/upnp/control/wanpppconn1";`
need to be changed to `string ControlUrl => "/upnp/control/wanpppconn1";`

Cheers, Stephan

Modell: FRITZ!Box Fon WLAN 7390
FRITZ!OS: 06.83

**Comment by inflames2k** [comment]
Hello,

thank you for the report. I used it with https, so I used the url "https://fritz.box" so I think there is the issue with the port and control urls assigned to.

I will change it so the control base path (/tr064) must be set manually. If not, it won't be used.
The port is only necessary when using the Interface without https or if the port has been changed.

**Comment by inflames2k** [comment]
Hello,

i decided to drop my idea of fixing the issue. I think it should be recommended to use SSL. So the URL to use would be **** https://fritz.box/tr064/upnp/control/wanpppconn1 ****

**Comment by inflames2k** [comment]
In the new version published today, port and hostname can be found by using the DeviceLocator. It returns all Fritzboxes found and you can initialize the services using found FritzDevice instances.
