### ISSUE TITLE
GetSpecificHostEntryAsync fails with SoapFaultException

### ISSUE THREAD

**Issue by textaligncenter** [inflames2k/PS.FritzBox.API#21]
I have the following code:
```
DeviceFactory factory = new DeviceFactory();
FritzDevice device = await factory.CreateDeviceAsync(System.Net.IPAddress.Parse("192.168.178.1"));
ConnectionSettings settings = new ConnectionSettings();
settings.BaseUrl = "192.168.178.1:49000";
settings.UserName = user;
settings.Password = password;
HostsClient client = await device.GetServiceClient<HostsClient>(settings);
var host = await client.GetSpecificHostEntryAsync(mac).ConfigureAwait(false);
```
The last line throws the following exception:

```
PS.FritzBox.API.SOAP.SoapFaultException: "s:Client; UPnPError 
{urn:dslforum-org:control-1-0}errorCode: 402
{urn:dslforum-org:control-1-0}errorDescription: Invalid Args
"
```

- The mac address definitely exists.
- It's a Fritzbox 7490 (OS 07.21)

Is there an issue or am I doing something wrong?

**Comment by inflames2k** [comment]
Hello,

no you're not doing anything wrong. Its a bug in code.
Will fix this as soon as possible.

If you want to fix it yourself. Bug is in line 64 of HostsClient, executing the SOAP Method "GetSpecificHostEntry" without parameters.

Correct call must be:
`XDocument document = await this.InvokeAsync("GetSpecificHostEntry", new SOAP.SoapRequestParameter("NewMACAddress", macAddress));`

**Comment by textaligncenter** [comment]
thx for your quick response :smiley: 👍

**Comment by inflames2k** [comment]
Have fixed the bug and uploaded a new version to nuget and the Github release.

Keep in mind that actually added interfaces (not the one allready existed in version 1.2.3) are unfinished and untestet.
