### ISSUE TITLE
Exception upon Login

### ISSUE THREAD

**Issue by minimalisticMe** [inflames2k/PS.FritzBox.API#25]
Hi,

I have a `FritzBox 7580` and want to connect to my `FritzBox` in order to enumerate my WLAN devices.
I have created a user account with some access rights (such as read and modify settings)
![grafik](https://user-images.githubusercontent.com/13404680/120934911-9e053180-c700-11eb-85f8-9a8ae6083280.png)

and I also have TR-064 enabled as shown below:
![grafik](https://user-images.githubusercontent.com/13404680/120934932-c0974a80-c700-11eb-8643-1dcbd0f06284.png)

But when I try to access either `DeviceConfigClient` or `DeviceInfoClient` I get an error message upon first calling a method, such as `var uuid = await deviceConfigClient.GenerateUUIDAsync();` or `var info = await deviceInfoClient.GetDeviceInfoAsync();`.

The error message reads:
```
Message: 
    System.Xml.XmlException : 'content-type' is an unexpected token. The expected token is '"' or '''. Line 4, position 18.

  Stack Trace: 
    XmlTextReaderImpl.Throw(Exception e)
    XmlTextReaderImpl.Throw(String res, String[] args)
    XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
    XmlTextReaderImpl.ParseAttributes()
    XmlTextReaderImpl.ParseElement()
    XmlTextReaderImpl.ParseElementContent()
    XContainer.ReadContentFrom(XmlReader r)
    XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
    XDocument.Load(XmlReader reader, LoadOptions options)
    XDocument.Load(TextReader textReader, LoadOptions options)
    XDocument.Load(TextReader textReader)
    SoapClient.ExecuteAsync(String xmlSOAP, Uri url, SoapRequestParameters parameters)
    SoapClient.InvokeAsync(Uri uri, SoapRequestParameters parameters)
    FritzTR64Client.InvokeAsync(String action, SoapRequestParameter[] parameter)
    DeviceConfigClient.GenerateUUIDAsync()
```

am I missing something or is my `FritzBox` not supported? I am not sure what to do with this error message.
What can I do in order to access my `FritzBox` with `PS.FritzBox.API`?

**Comment by inflames2k** [comment]
Der Fehler kommt mir ein wenig bekannt vor von einem anderen Methodenaufruf.
Hast du mal eine andere Schnittstellenmethode probiert?
Außerdem wäre noch interessant, wie du den Client erstellst.

The error looks a bit familiar from another method call.
Have you tried another interface method?
Also, it would be interesting to know how you create the client.

Da mir unklar ist, wie du die Clients generierst. Probier mal bitte unter Verwendung von DeviceLocator.FindDevicesAsync() alle Fritz.Boxen in deinem Netzwerk aufzulisten. Als Ergebnis bekommst du eine Auflistung von Objekten des Typs FritzDevice.

Über diesen kannst du dir die Clients erstellen lassen. Gib mal bitte bescheid, ob es damit funktioniert. Dazu folgender Code:

Since it is unclear to me how you generate the clients. Please try to list all Fritz.Boxes in your network using DeviceLocator.FindDevicesAsync(). As a result you get a list of objects of the type FritzDevice.

You can use this to create the clients. Please let me know if it works. The following code:

```c#
DeviceLocator locator = new DeviceLocator();
var devices = await locater.DiscoverAsync();
if(devices.Count() > 0)
{
    var device = devices.First();
    ConnectionSettings settings = new ConnectionSettings()
    {
       UserName = "inflames2k";
       Password = "secret";
    };

    var client = await device.GetServiceClient<DeviceInfoClient>(settings);
    var info = await client.GetInfoAsync();
}
```

**Comment by minimalisticMe** [comment]
Hi, running your code (I had to adapt it slightly) I still get the same error message.
The code I executed:
```
private static async Task Connect(string username, string password)
{
    DeviceLocator locator = new DeviceLocator();
    var devices = await locator.DiscoverAsync();
    if (devices.Count() > 0)
    {
        var device = devices.First();
        ConnectionSettings settings = new ConnectionSettings()
        {
            UserName = username,
            Password = password
        };

        var client = await device.GetServiceClient<DeviceInfoClient>(settings);
        //var info = await client.GetInfoAsync();
    }
}
```

The error occurs in line `var devices = await locator.DiscoverAsync();`.

Der Fehler tritt weiterhin mit der Fehlermeldung `XmlException: Unerwartetes Token '>'. Das erwartete Token ist '"' oder '''. Zeile 1, Position 62.` auf.
Auch wenn ich versuche, die Geräte nach der "neuen" Methode (schlägt mir VS zumindest vor) zu verwenden mit `FritzDevice.LocateDevicesAsync`.

Kann es vielleicht an spezifischen FritzBox-Einstellungen liegen?
Ich kann mich nicht daran erinnern, da irgendwas geändert zu haben, aber nachschauen bei Ideen schadet nicht.

**Comment by inflames2k** [comment]
Naja für mich klingt das ein wenig als würde versucht auf die falsche Url zuzugreifen bzw. die FritzBox gibt eine falsche Rückgabe.
Deswegen hatte ich ja den Weg über den DeviceLocator genannt, weil der schon mal die korrekte Url zusammen baut.

Da ich leider keine 7580 zur Hand habe kann ich auch nicht schauen, was das Problem ist. Die Einstellungen würde ich mal ausschließen.
Einziges was ich noch vorschlagen könnte, ist dass du dir den SourceCode runter lädst und mal mit dem Debugger reinschaust, wo das Problem liegt.

Speziell wäre interessant, was als Rückgabe nach 
       SoapClient.ExecuteAsync(String xmlSOAP, Uri url, SoapRequestParameters parameters)
im Ergebnis steht.

**Comment by minimalisticMe** [comment]
Wunderbar, ein Heisenberg-Problem: Wenn ich das Projekt _PS.FritzBox.API.CMD_ direkt ausführe, knallt es, wenn ich es genauer anschaue (einzeln durchiterieren), findet es meine FritzBox mit der richtigen IP und Port.

Die SoapResonse sieht folgendermaßen aus:
```
{<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:GetSecurityPortResponse xmlns:u="urn:dslforum-org:service:DeviceInfo:1">
      <NewSecurityPort>49443</NewSecurityPort>
    </u:GetSecurityPortResponse>
  </s:Body>
</s:Envelope>}
```

Da es im Fehlerfall etwas braucht, könnte es vielleicht ein Deadlock sein, der dann nach 10 Sekunden durch `Task waitTask = Task.Delay(TimeSpan.FromSeconds(10));` gelöst wird?

**Update**
Wenn ich nur einen Breakpoint in `SoapClient.ExecuteAsync` setze (ohne Pause/Breakpoint davor), erhalte ich als `HttpResponseMessage` folgenden Inhalt:
```
{StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: close
  Date: Tue, 22 Jun 2021 16:37:04 GMT
  ETag: "608eb5a6-254"
  Server: nginx
  Content-Length: 596
  Content-Type: text/html
}}
```

und danach fliegt der Fehler in der Zeile `XDocument soapResponse = XDocument.Load(sr); `.

Der Call-stack (aus der Fehlemeldung):
```
This exception was originally thrown at this call stack:
    [External Code]
    PS.FritzBox.API.SOAP.SoapClient.ExecuteAsync(string, System.Uri, PS.FritzBox.API.SOAP.SoapRequestParameters) in SoapClient.cs
    [External Code]
    PS.FritzBox.API.SOAP.SoapClient.InvokeAsync(System.Uri, PS.FritzBox.API.SOAP.SoapRequestParameters) in SoapClient.cs
    [External Code]
    PS.FritzBox.API.Base.FritzTR64Client.InvokeAsync(string, PS.FritzBox.API.SOAP.SoapRequestParameter[]) in FritzTR64Client.cs
    [External Code]
    PS.FritzBox.API.DeviceInfoClient.GetSecurityPortAsync() in DeviceInfoClient.cs
    [External Code]
    PS.FritzBox.API.FritzDevice.ParseResponseAsync(System.Net.IPAddress, string) in FritzDevice.cs
    ...
    [Call Stack Truncated]
```

Zur Info: Als `Uri` wird `http://192.168.188.55/upnp/control/deviceinfo` (meine WLAN-IP, FritBox endet auf .1) übergeben.

**Comment by inflames2k** [comment]
Zwei Sachen. Nimm die CMD nicht als Master. Dass die so nicht in Ordnung ist, ist bekannt.
Hattest du die letzte Version von Nuget genommen? 

By the way empfehle ich den Security Port auf jeden Fall zu verwenden.

Wobei ich den Fehler soweit grad nicht nachstellen kann. - Ich nutze die 7530 und hier funktioniert soweit alles wie es soll.

**Comment by inflames2k** [comment]
Hat sich hier denn etwas neues ergeben?

**Comment by inflames2k** [comment]
Da hier keinerlei weitere Info erfolgt, ob das Problem mittlerweile gelöst ist und seitens der API kein Fehler feststellbar ist... Schließe ich hier.

**Comment by minimalisticMe** [comment]
Hallo, ich habe wieder in die Thematik reingeschaut.

Diesmal habe ich das Projekt `PS.FritzBox.API` vom `master` Branch heruntergeladen und im Projekt verlinkt.
Ich habe ein Minimales Projekt erzeugt mit
```
static async Task Main(string[] args)
{
    Console.WriteLine("Hello World!");

    var username = "fritzAPI";
    var password = "<entfernt>";
    var fritzUrl = "https://fritz.box";
    var timeOut = 10000;

    DeviceInfoClient client = new DeviceInfoClient(fritzUrl, timeOut, username, password);
    DeviceInfo info = await client.GetDeviceInfoAsync();
}
```

Wenn ich `https://fritz.box` mit den Credentials in Firefox aufrufe, bekomme ich zu erst eine Warnung wegen dem Selbsignierten Zertifikat der Firtzbox (habe da nichts geändert, das ist wohl Standard) und kann mich mit den Credentials erfolgreich via Firefox einloggen.

Wenn ich das Projekt ausführe, erhalte ich in der Funktion `private async Task<XDocument> ExecuteAsync(string xmlSOAP, Uri url, SoapRequestParameters parameters)` in der Datei `SoapClient.cs` einen Fehler in der Zeile `XDocument soapResponse = XDocument.Load(sr);`.

Die `response` hat den Status Code 404, wenn ich mir den Stream-Inhalt ausgebe, dann steht da das folgende:
```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv=content-type content="text/html; charset=utf-8" />
<meta http-equiv="Cache-Control" content="private, no-transform" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="format-detection" content="telephone=no" />
<meta http-equiv="x-rim-auto-match" content="none" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui" />
<meta name="mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta http-equiv="cleartype" content="on">
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
<link rel="apple-touch-icon" href="/css/rd/logos/logo_fritzDiamond.png" />
<link rel="apple-touch-startup-image" href="/css/rd/logos/logo_fritzDiamond.png">
<link rel="stylesheet" type="text/css" href="/css/rd/singleside_old.css"/>
<title>FRITZ!Box</title>
</head>
<body>
<div id="main_page_all">
<header class="" name="" id="blueBarBox">
<div class="blue_bar_titel" name="" id="blueBarTitel">
FRITZ!Box
</div>
</header>
<div id="page_content_no_menu_box">
<div class="area_box">
<div class="blue_bar_back" >
<div><h2>FRITZ!Box</h2></div>
</div>
<div class="page_content">
<p>Die angegebene URL wurde nicht gefunden. Sie werden auf die Startseite der FRITZ!Box weitergeleitet.</p>
<p>Falls Sie nicht automatisch auf die Startseite der FRITZ!Box weitergeleitet werden, klicken Sie <a href="/">hier</a>.</p>
<br>
</div>
</div>
</div>
</div>
<script>
window.setTimeout(function () {
window.location.href = "/";
}, 10000);
</script>
</body>
</html>
```

Das erhalte ich auch in Firefox, wenn ich versuche, die URL `https://fritz.box/upnp/control/deviceinfo` aufzurufen.

Vielleicht fällt mir die Tage noch was dazu ein.

**Comment by minimalisticMe** [comment]
Eine Besonderheit hat mein Setup noch: Die FritzBox hängt nicht direkt am Internet, sondern bekommt das Internet über den WAN Anschluss.
Das sollte allerdings nichts ändern, der Endpunkt `https://fritz.box` ist nach wie vor eindeutig definiert.

**Comment by inflames2k** [comment]
Ich empfehle dir aber weiterhin den DeviceLocator zu verwenden zur Erzeugung der URL. Denn der direkte Konstruktor verwendet unter Umständen nicht den korrekten Port. Alternativ die DeviceFactory.
