### ISSUE TITLE
Typos in WANPPPConnectionClient.cs

### ISSUE THREAD

**Issue by Stephanowicz** [inflames2k/PS.FritzBox.API#3]
Hi,

there some typos in WANPPPConnectionClient.cs:

In function` public async Task<WANPPPConnectionInfo> GetInfo()`

line 41: "NewUp**T**ime" needs to be "NewUp**t**ime"
line 48: "UpstreamMaxBitRate" needs to be "**New**UpstreamMaxBitRate"

I also had crashes with the `Convert.ToBoolean` ... dunno - I changed it e.g. to `document.Descendants("NewRSIPAvailable").First().Value == "0" ? false:true;`

Cheers, Stephan

**Comment by inflames2k** [comment]
Hello,

thank you for your report. The class wasn't tested yet and only checked in so I won't lose it. So I knew that it won't do its work perfectly. 

In any case I will fix this.

**Comment by inflames2k** [comment]
Hello,

i corrected the typos. The client is still untested so don't be worried if it's not working properly.
