### ISSUE TITLE
ForceTermination gives internal server error

### ISSUE THREAD

**Issue by Stephanowicz** [inflames2k/PS.FritzBox.API#4]
Hi,
when calling ForceTermination in WANPPPConnectionClient.cs I get an unhandled error with internal server error somewhere in the details. (As it is an async call there's no more info - though, while writing this I'm realizing I could change it to a synchron call... xD )

So as a simple workaround I put it in a try-catch block:
```
        public void ForceTermination()
        {
            try
            {
                this.Invoke("ForceTermination", null);
            }
            catch (Exception)
            {

                ;
            }
        }

```
I also removed the async here - I don't think it's necessary...?

Although there is an error, the connection gets terminated....

Any idea why this gives an internal server error?

Cheers, Stephan

**Comment by inflames2k** [comment]
Am I understanding this correct? The connection is terminated but there is also thrown an internal server error?

I will check and fix it if I can find the issue.

**Comment by Stephanowicz** [comment]
Yep - recently I found that "/igdupnp/control/WANIPConn1"  (igdconnSCPD.xml) also has these commands, and they don't throw an error...
```

namespace PS.FritzBox.API
{
    /// <summary>
    /// class for getting informations about the wan ppp connection
    /// </summary>
    public class WANIPConnectionClient1 : FritzTR64Client
    {
        public WANIPConnectionClient1(string url, int timeout) : base(url, timeout)
        {
        }

        /// <summary>
        /// Sets the control url
        /// </summary>
        protected override string ControlUrl => "/igdupnp/control/WANIPConn1"; //igdconnSCPD.xml

        /// <summary>
        /// Sets the request namespace
        /// </summary>                                 
        protected override string RequestNameSpace => "urn:schemas-upnp-org:service:WANIPConnection:1";

        /// <summary>
        /// Method to force the termination of the ppp connection
        /// </summary>
        public void ForceTermination()
        {
            try
            {
                this.Invoke("ForceTermination", null);
            }
            catch (Exception)
            {

                ;
            }
        }

        /// <summary>
        /// Method to request the termination of the ppp connection
        /// </summary>
        public void RequestTermination()
        {
            try
            {
                this.Invoke("RequestTermination", null);
            }
            catch (Exception)
            {

                ;
            }
        }
        /// <summary>
        /// Method to request a ppp connection
        /// </summary>
        public async void RequestConnection()
        {
            XDocument document = await this.Invoke("RequestConnection", null);
        }
    }
}

```
Cheers, Stephan

**Comment by inflames2k** [comment]
I searched for informations on this issue and only found that the ForceTermination-call and the RequestConnection-call from WANPPPConnection are throwing an internal server error sometimes. But the calls are executed if no other error occures.

**Comment by inflames2k** [comment]
During some tests and changes to the API I figured out the reason for the internal server error. On calling force termination the device throws an error because of the disconnect progress. - Something may be wrong implemented on the service. So there is nothing I can do to fix this.
