### ISSUE TITLE
System.XML.XMLException

### ISSUE THREAD

**Issue by LuHe78** [inflames2k/PS.FritzBox.API#8]
The api looks really intresting, thanks for your work. 
Sadly i get the Exception System.XML.XMLException "Root Element does not exist".

This is the code

Dim client As New PS.FritzBox.API.WANCommonInterfaceConfigClient("http://192.168.0.1", 10000)
client.UserName = "Name"
client.Password = "Passwort"
Dim mon As OnlineMonitorInfo = Await client.GetOnlineMonitor(0)

Thanks for your help

**Comment by inflames2k** [comment]
Hello,

have you tried accessing the url https://fritz.box/tr064/tr64desc.xml or http://fritz.box:49000/tr64desc.xml?
If the xml file is not accessible you have to check the ports that your device uses for providing the description.

In case that the security port on your device has been changed you have to append the security port to the base url.

I recommend using the secure connection "https://fritz.box". 

You can try my application I provide for using the online monitor. It's located at https://github.com/inflames2k/PS.FritzBox.NetworkMonitor providing a release download. The connection settings are set in the config file "PS.FritzBox.NetworkMonitor.exe.config".

**Comment by LuHe78** [comment]
Hello 

Thanks for your help. It works with the secure connection "https://192.168.0.1"

**Comment by inflames2k** [comment]
In the next version (you can see in the development branch) I will change some connection related settings. The connection will be made by host name and port and the client classes will get the secure connection by them self.

Also a device search and service search will be added.
